---
# tasks file for ansible-glusterfs-client
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config.yml
  when: glusterfs_client_config|bool
